// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: expense.proto

package expensepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckApproverAssignmentsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckApproverAssignmentsRequest) Reset() {
	*x = CheckApproverAssignmentsRequest{}
	mi := &file_expense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckApproverAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckApproverAssignmentsRequest) ProtoMessage() {}

func (x *CheckApproverAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckApproverAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*CheckApproverAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{0}
}

func (x *CheckApproverAssignmentsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CheckApproverAssignmentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckApproverAssignmentsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HasActiveRules bool                   `protobuf:"varint,1,opt,name=has_active_rules,json=hasActiveRules,proto3" json:"has_active_rules,omitempty"` // true = member is still an approver on live rules
	Rules          []*ApprovalRule        `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckApproverAssignmentsResponse) Reset() {
	*x = CheckApproverAssignmentsResponse{}
	mi := &file_expense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckApproverAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckApproverAssignmentsResponse) ProtoMessage() {}

func (x *CheckApproverAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckApproverAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*CheckApproverAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{1}
}

func (x *CheckApproverAssignmentsResponse) GetHasActiveRules() bool {
	if x != nil {
		return x.HasActiveRules
	}
	return false
}

func (x *CheckApproverAssignmentsResponse) GetRules() []*ApprovalRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ApprovalRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // UUID of the approval rule
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // UUID of the project; empty = organization default rule
	Step          int32                  `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRule) Reset() {
	*x = ApprovalRule{}
	mi := &file_expense_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRule) ProtoMessage() {}

func (x *ApprovalRule) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRule.ProtoReflect.Descriptor instead.
func (*ApprovalRule) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{2}
}

func (x *ApprovalRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApprovalRule) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ApprovalRule) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

type ReassignApproverRulesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	FromUserId     string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // member being removed
	ToUserId       string                 `protobuf:"bytes,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`       // replacement approver chosen by the admin
	ActorId        string                 `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`            // admin who made the decision (for the audit event)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReassignApproverRulesRequest) Reset() {
	*x = ReassignApproverRulesRequest{}
	mi := &file_expense_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReassignApproverRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReassignApproverRulesRequest) ProtoMessage() {}

func (x *ReassignApproverRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReassignApproverRulesRequest.ProtoReflect.Descriptor instead.
func (*ReassignApproverRulesRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{3}
}

func (x *ReassignApproverRulesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ReassignApproverRulesRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *ReassignApproverRulesRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *ReassignApproverRulesRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type ReassignApproverRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reassigned    int64                  `protobuf:"varint,1,opt,name=reassigned,proto3" json:"reassigned,omitempty"` // number of rules moved
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReassignApproverRulesResponse) Reset() {
	*x = ReassignApproverRulesResponse{}
	mi := &file_expense_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReassignApproverRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReassignApproverRulesResponse) ProtoMessage() {}

func (x *ReassignApproverRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReassignApproverRulesResponse.ProtoReflect.Descriptor instead.
func (*ReassignApproverRulesResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{4}
}

func (x *ReassignApproverRulesResponse) GetReassigned() int64 {
	if x != nil {
		return x.Reassigned
	}
	return 0
}

var File_expense_proto protoreflect.FileDescriptor

const file_expense_proto_rawDesc = "" +
	"\n" +
	"\rexpense.proto\x12\n" +
	"expense.v1\"c\n" +
	"\x1fCheckApproverAssignmentsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"|\n" +
	" CheckApproverAssignmentsResponse\x12(\n" +
	"\x10has_active_rules\x18\x01 \x01(\bR\x0ehasActiveRules\x12.\n" +
	"\x05rules\x18\x02 \x03(\v2\x18.expense.v1.ApprovalRuleR\x05rules\"Q\n" +
	"\fApprovalRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x05R\x04step\"\xa2\x01\n" +
	"\x1cReassignApproverRulesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\tR\btoUserId\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\"?\n" +
	"\x1dReassignApproverRulesResponse\x12\x1e\n" +
	"\n" +
	"reassigned\x18\x01 \x01(\x03R\n" +
	"reassigned2\xf5\x01\n" +
	"\x0eExpenseService\x12u\n" +
	"\x18CheckApproverAssignments\x12+.expense.v1.CheckApproverAssignmentsRequest\x1a,.expense.v1.CheckApproverAssignmentsResponse\x12l\n" +
	"\x15ReassignApproverRules\x12(.expense.v1.ReassignApproverRulesRequest\x1a).expense.v1.ReassignApproverRulesResponseBCZAgithub.com/disillusioned-labs/platform/contract/expense;expensepbb\x06proto3"

var (
	file_expense_proto_rawDescOnce sync.Once
	file_expense_proto_rawDescData []byte
)

func file_expense_proto_rawDescGZIP() []byte {
	file_expense_proto_rawDescOnce.Do(func() {
		file_expense_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expense_proto_rawDesc), len(file_expense_proto_rawDesc)))
	})
	return file_expense_proto_rawDescData
}

var file_expense_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_expense_proto_goTypes = []any{
	(*CheckApproverAssignmentsRequest)(nil),  // 0: expense.v1.CheckApproverAssignmentsRequest
	(*CheckApproverAssignmentsResponse)(nil), // 1: expense.v1.CheckApproverAssignmentsResponse
	(*ApprovalRule)(nil),                     // 2: expense.v1.ApprovalRule
	(*ReassignApproverRulesRequest)(nil),     // 3: expense.v1.ReassignApproverRulesRequest
	(*ReassignApproverRulesResponse)(nil),    // 4: expense.v1.ReassignApproverRulesResponse
}
var file_expense_proto_depIdxs = []int32{
	2, // 0: expense.v1.CheckApproverAssignmentsResponse.rules:type_name -> expense.v1.ApprovalRule
	0, // 1: expense.v1.ExpenseService.CheckApproverAssignments:input_type -> expense.v1.CheckApproverAssignmentsRequest
	3, // 2: expense.v1.ExpenseService.ReassignApproverRules:input_type -> expense.v1.ReassignApproverRulesRequest
	1, // 3: expense.v1.ExpenseService.CheckApproverAssignments:output_type -> expense.v1.CheckApproverAssignmentsResponse
	4, // 4: expense.v1.ExpenseService.ReassignApproverRules:output_type -> expense.v1.ReassignApproverRulesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_expense_proto_init() }
func file_expense_proto_init() {
	if File_expense_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expense_proto_rawDesc), len(file_expense_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expense_proto_goTypes,
		DependencyIndexes: file_expense_proto_depIdxs,
		MessageInfos:      file_expense_proto_msgTypes,
	}.Build()
	File_expense_proto = out.File
	file_expense_proto_goTypes = nil
	file_expense_proto_depIdxs = nil
}
