// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: expense.proto

package expensepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExpenseService_CheckApproverAssignments_FullMethodName = "/expense.v1.ExpenseService/CheckApproverAssignments"
	ExpenseService_ReassignApproverRules_FullMethodName    = "/expense.v1.ExpenseService/ReassignApproverRules"
)

// ExpenseServiceClient is the client API for ExpenseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExpenseService is served by expense and called by identity (REVERSE
// direction of IdentityService): approval rules live in the expense
// database, so only expense can answer "is this member still an active
// approver?". Identity calls CheckApproverAssignments before committing a
// member removal and ReassignApproverRules when the admin picks a
// replacement ("keluarkan + alihkan ke ___").
type ExpenseServiceClient interface {
	CheckApproverAssignments(ctx context.Context, in *CheckApproverAssignmentsRequest, opts ...grpc.CallOption) (*CheckApproverAssignmentsResponse, error)
	ReassignApproverRules(ctx context.Context, in *ReassignApproverRulesRequest, opts ...grpc.CallOption) (*ReassignApproverRulesResponse, error)
}

type expenseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExpenseServiceClient(cc grpc.ClientConnInterface) ExpenseServiceClient {
	return &expenseServiceClient{cc}
}

func (c *expenseServiceClient) CheckApproverAssignments(ctx context.Context, in *CheckApproverAssignmentsRequest, opts ...grpc.CallOption) (*CheckApproverAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckApproverAssignmentsResponse)
	err := c.cc.Invoke(ctx, ExpenseService_CheckApproverAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expenseServiceClient) ReassignApproverRules(ctx context.Context, in *ReassignApproverRulesRequest, opts ...grpc.CallOption) (*ReassignApproverRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReassignApproverRulesResponse)
	err := c.cc.Invoke(ctx, ExpenseService_ReassignApproverRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExpenseServiceServer is the server API for ExpenseService service.
// All implementations must embed UnimplementedExpenseServiceServer
// for forward compatibility.
//
// ExpenseService is served by expense and called by identity (REVERSE
// direction of IdentityService): approval rules live in the expense
// database, so only expense can answer "is this member still an active
// approver?". Identity calls CheckApproverAssignments before committing a
// member removal and ReassignApproverRules when the admin picks a
// replacement ("keluarkan + alihkan ke ___").
type ExpenseServiceServer interface {
	CheckApproverAssignments(context.Context, *CheckApproverAssignmentsRequest) (*CheckApproverAssignmentsResponse, error)
	ReassignApproverRules(context.Context, *ReassignApproverRulesRequest) (*ReassignApproverRulesResponse, error)
	mustEmbedUnimplementedExpenseServiceServer()
}

// UnimplementedExpenseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExpenseServiceServer struct{}

func (UnimplementedExpenseServiceServer) CheckApproverAssignments(context.Context, *CheckApproverAssignmentsRequest) (*CheckApproverAssignmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckApproverAssignments not implemented")
}
func (UnimplementedExpenseServiceServer) ReassignApproverRules(context.Context, *ReassignApproverRulesRequest) (*ReassignApproverRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReassignApproverRules not implemented")
}
func (UnimplementedExpenseServiceServer) mustEmbedUnimplementedExpenseServiceServer() {}
func (UnimplementedExpenseServiceServer) testEmbeddedByValue()                        {}

// UnsafeExpenseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExpenseServiceServer will
// result in compilation errors.
type UnsafeExpenseServiceServer interface {
	mustEmbedUnimplementedExpenseServiceServer()
}

func RegisterExpenseServiceServer(s grpc.ServiceRegistrar, srv ExpenseServiceServer) {
	// If the following call panics, it indicates UnimplementedExpenseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExpenseService_ServiceDesc, srv)
}

func _ExpenseService_CheckApproverAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckApproverAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).CheckApproverAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpenseService_CheckApproverAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).CheckApproverAssignments(ctx, req.(*CheckApproverAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExpenseService_ReassignApproverRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReassignApproverRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpenseServiceServer).ReassignApproverRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExpenseService_ReassignApproverRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpenseServiceServer).ReassignApproverRules(ctx, req.(*ReassignApproverRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExpenseService_ServiceDesc is the grpc.ServiceDesc for ExpenseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExpenseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "expense.v1.ExpenseService",
	HandlerType: (*ExpenseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckApproverAssignments",
			Handler:    _ExpenseService_CheckApproverAssignments_Handler,
		},
		{
			MethodName: "ReassignApproverRules",
			Handler:    _ExpenseService_ReassignApproverRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expense.proto",
}
