// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: member.proto

package memberpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemberService_CheckApproverAssignments_FullMethodName = "/identity.member.v1.MemberService/CheckApproverAssignments"
	MemberService_ReassignApproverRules_FullMethodName    = "/identity.member.v1.MemberService/ReassignApproverRules"
)

// MemberServiceClient is the client API for MemberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MemberService is served by expense and called by identity (REVERSE
// direction of IdentityService): approval rules live in the expense
// database, so only expense can answer "is this member still an active
// approver?". Identity calls CheckApproverAssignments before committing a
// member removal and ReassignApproverRules when the admin picks a
// replacement ("keluarkan + alihkan ke ___").
type MemberServiceClient interface {
	CheckApproverAssignments(ctx context.Context, in *CheckApproverAssignmentsRequest, opts ...grpc.CallOption) (*CheckApproverAssignmentsResponse, error)
	ReassignApproverRules(ctx context.Context, in *ReassignApproverRulesRequest, opts ...grpc.CallOption) (*ReassignApproverRulesResponse, error)
}

type memberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemberServiceClient(cc grpc.ClientConnInterface) MemberServiceClient {
	return &memberServiceClient{cc}
}

func (c *memberServiceClient) CheckApproverAssignments(ctx context.Context, in *CheckApproverAssignmentsRequest, opts ...grpc.CallOption) (*CheckApproverAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckApproverAssignmentsResponse)
	err := c.cc.Invoke(ctx, MemberService_CheckApproverAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) ReassignApproverRules(ctx context.Context, in *ReassignApproverRulesRequest, opts ...grpc.CallOption) (*ReassignApproverRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReassignApproverRulesResponse)
	err := c.cc.Invoke(ctx, MemberService_ReassignApproverRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberServiceServer is the server API for MemberService service.
// All implementations must embed UnimplementedMemberServiceServer
// for forward compatibility.
//
// MemberService is served by expense and called by identity (REVERSE
// direction of IdentityService): approval rules live in the expense
// database, so only expense can answer "is this member still an active
// approver?". Identity calls CheckApproverAssignments before committing a
// member removal and ReassignApproverRules when the admin picks a
// replacement ("keluarkan + alihkan ke ___").
type MemberServiceServer interface {
	CheckApproverAssignments(context.Context, *CheckApproverAssignmentsRequest) (*CheckApproverAssignmentsResponse, error)
	ReassignApproverRules(context.Context, *ReassignApproverRulesRequest) (*ReassignApproverRulesResponse, error)
	mustEmbedUnimplementedMemberServiceServer()
}

// UnimplementedMemberServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemberServiceServer struct{}

func (UnimplementedMemberServiceServer) CheckApproverAssignments(context.Context, *CheckApproverAssignmentsRequest) (*CheckApproverAssignmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckApproverAssignments not implemented")
}
func (UnimplementedMemberServiceServer) ReassignApproverRules(context.Context, *ReassignApproverRulesRequest) (*ReassignApproverRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReassignApproverRules not implemented")
}
func (UnimplementedMemberServiceServer) mustEmbedUnimplementedMemberServiceServer() {}
func (UnimplementedMemberServiceServer) testEmbeddedByValue()                       {}

// UnsafeMemberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemberServiceServer will
// result in compilation errors.
type UnsafeMemberServiceServer interface {
	mustEmbedUnimplementedMemberServiceServer()
}

func RegisterMemberServiceServer(s grpc.ServiceRegistrar, srv MemberServiceServer) {
	// If the following call panics, it indicates UnimplementedMemberServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemberService_ServiceDesc, srv)
}

func _MemberService_CheckApproverAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckApproverAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).CheckApproverAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberService_CheckApproverAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).CheckApproverAssignments(ctx, req.(*CheckApproverAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_ReassignApproverRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReassignApproverRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).ReassignApproverRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberService_ReassignApproverRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).ReassignApproverRules(ctx, req.(*ReassignApproverRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemberService_ServiceDesc is the grpc.ServiceDesc for MemberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.member.v1.MemberService",
	HandlerType: (*MemberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckApproverAssignments",
			Handler:    _MemberService_CheckApproverAssignments_Handler,
		},
		{
			MethodName: "ReassignApproverRules",
			Handler:    _MemberService_ReassignApproverRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "member.proto",
}
