// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: document.proto

package ocrpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentStatus int32

const (
	DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED  DocumentStatus = 0
	DocumentStatus_DOCUMENT_STATUS_QUEUED       DocumentStatus = 1
	DocumentStatus_DOCUMENT_STATUS_PROCESSING   DocumentStatus = 2
	DocumentStatus_DOCUMENT_STATUS_COMPLETED    DocumentStatus = 3
	DocumentStatus_DOCUMENT_STATUS_NEEDS_REVIEW DocumentStatus = 4
	DocumentStatus_DOCUMENT_STATUS_FAILED       DocumentStatus = 5
)

// Enum value maps for DocumentStatus.
var (
	DocumentStatus_name = map[int32]string{
		0: "DOCUMENT_STATUS_UNSPECIFIED",
		1: "DOCUMENT_STATUS_QUEUED",
		2: "DOCUMENT_STATUS_PROCESSING",
		3: "DOCUMENT_STATUS_COMPLETED",
		4: "DOCUMENT_STATUS_NEEDS_REVIEW",
		5: "DOCUMENT_STATUS_FAILED",
	}
	DocumentStatus_value = map[string]int32{
		"DOCUMENT_STATUS_UNSPECIFIED":  0,
		"DOCUMENT_STATUS_QUEUED":       1,
		"DOCUMENT_STATUS_PROCESSING":   2,
		"DOCUMENT_STATUS_COMPLETED":    3,
		"DOCUMENT_STATUS_NEEDS_REVIEW": 4,
		"DOCUMENT_STATUS_FAILED":       5,
	}
)

func (x DocumentStatus) Enum() *DocumentStatus {
	p := new(DocumentStatus)
	*p = x
	return p
}

func (x DocumentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_document_proto_enumTypes[0].Descriptor()
}

func (DocumentStatus) Type() protoreflect.EnumType {
	return &file_document_proto_enumTypes[0]
}

func (x DocumentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentStatus.Descriptor instead.
func (DocumentStatus) EnumDescriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

type FieldStatus int32

const (
	FieldStatus_FIELD_STATUS_UNSPECIFIED    FieldStatus = 0
	FieldStatus_FIELD_STATUS_EXTRACTED      FieldStatus = 1
	FieldStatus_FIELD_STATUS_LOW_CONFIDENCE FieldStatus = 2
	FieldStatus_FIELD_STATUS_MISSING        FieldStatus = 3
	FieldStatus_FIELD_STATUS_INVALID        FieldStatus = 4 // malformed format (date failed to parse, etc.)
)

// Enum value maps for FieldStatus.
var (
	FieldStatus_name = map[int32]string{
		0: "FIELD_STATUS_UNSPECIFIED",
		1: "FIELD_STATUS_EXTRACTED",
		2: "FIELD_STATUS_LOW_CONFIDENCE",
		3: "FIELD_STATUS_MISSING",
		4: "FIELD_STATUS_INVALID",
	}
	FieldStatus_value = map[string]int32{
		"FIELD_STATUS_UNSPECIFIED":    0,
		"FIELD_STATUS_EXTRACTED":      1,
		"FIELD_STATUS_LOW_CONFIDENCE": 2,
		"FIELD_STATUS_MISSING":        3,
		"FIELD_STATUS_INVALID":        4,
	}
)

func (x FieldStatus) Enum() *FieldStatus {
	p := new(FieldStatus)
	*p = x
	return p
}

func (x FieldStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_document_proto_enumTypes[1].Descriptor()
}

func (FieldStatus) Type() protoreflect.EnumType {
	return &file_document_proto_enumTypes[1]
}

func (x FieldStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldStatus.Descriptor instead.
func (FieldStatus) EnumDescriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

type SubmitDocumentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // REQUIRED - submit idempotency key; enforced HERE (documents.idempotency_key UNIQUE)
	ExternalRef    string                 `protobuf:"bytes,2,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`          // the caller's business ID - echoed back unchanged on every event
	SchemaId       string                 `protobuf:"bytes,3,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`                   // result of the gateway's mapping: "receipt@1", "invoice@1" - the engine knows no business names
	CallerId       string                 `protobuf:"bytes,4,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`                   // originating caller ("expense", etc.) - for audit in the engine AND return routing (echoed in the event)
	Source         *FileSource            `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitDocumentRequest) Reset() {
	*x = SubmitDocumentRequest{}
	mi := &file_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDocumentRequest) ProtoMessage() {}

func (x *SubmitDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDocumentRequest.ProtoReflect.Descriptor instead.
func (*SubmitDocumentRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitDocumentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SubmitDocumentRequest) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *SubmitDocumentRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *SubmitDocumentRequest) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *SubmitDocumentRequest) GetSource() *FileSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type FileSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`                              // the caller's object storage bucket - MUST be listed in ocr's config allowlist
	StoragePath   string                 `protobuf:"bytes,2,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"` // object path in the bucket (not a URL) - read directly with ocr's own READ-ONLY credentials
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	DeclaredMime  string                 `protobuf:"bytes,4,opt,name=declared_mime,json=declaredMime,proto3" json:"declared_mime,omitempty"` // a hint only - ocr validates the magic bytes itself
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSource) Reset() {
	*x = FileSource{}
	mi := &file_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSource) ProtoMessage() {}

func (x *FileSource) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSource.ProtoReflect.Descriptor instead.
func (*FileSource) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

func (x *FileSource) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *FileSource) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *FileSource) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileSource) GetDeclaredMime() string {
	if x != nil {
		return x.DeclaredMime
	}
	return ""
}

type SubmitDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Status        DocumentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=document.v1.DocumentStatus" json:"status,omitempty"` // always QUEUED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDocumentResponse) Reset() {
	*x = SubmitDocumentResponse{}
	mi := &file_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDocumentResponse) ProtoMessage() {}

func (x *SubmitDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDocumentResponse.ProtoReflect.Descriptor instead.
func (*SubmitDocumentResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *SubmitDocumentResponse) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Status        DocumentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=document.v1.DocumentStatus" json:"status,omitempty"`
	Result        *DocumentResult        `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // null until COMPLETED / NEEDS_REVIEW
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`   // set when FAILED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{4}
}

func (x *GetDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetDocumentResponse) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

func (x *GetDocumentResponse) GetResult() *DocumentResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetDocumentResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DocumentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	AvgConfidence float64                `protobuf:"fixed64,2,opt,name=avg_confidence,json=avgConfidence,proto3" json:"avg_confidence,omitempty"`
	Fields        []*ExtractedField      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Issues        []*Issue               `protobuf:"bytes,4,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentResult) Reset() {
	*x = DocumentResult{}
	mi := &file_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResult) ProtoMessage() {}

func (x *DocumentResult) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResult.ProtoReflect.Descriptor instead.
func (*DocumentResult) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentResult) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *DocumentResult) GetAvgConfidence() float64 {
	if x != nil {
		return x.AvgConfidence
	}
	return 0
}

func (x *DocumentResult) GetFields() []*ExtractedField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DocumentResult) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type ExtractedField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // "merchant", "date", "total", ...
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`       // text; for money use amount + currency (below)
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`    // money: BIGINT smallest unit (IDR = whole rupiah) - platform money convention
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"` // ISO 4217, money fields only
	Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Status        FieldStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=document.v1.FieldStatus" json:"status,omitempty"`
	Bbox          *BoundingBox           `protobuf:"bytes,7,opt,name=bbox,proto3" json:"bbox,omitempty"` // source line location in the image - for the review UI
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractedField) Reset() {
	*x = ExtractedField{}
	mi := &file_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractedField) ProtoMessage() {}

func (x *ExtractedField) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractedField.ProtoReflect.Descriptor instead.
func (*ExtractedField) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{6}
}

func (x *ExtractedField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtractedField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ExtractedField) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExtractedField) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ExtractedField) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ExtractedField) GetStatus() FieldStatus {
	if x != nil {
		return x.Status
	}
	return FieldStatus_FIELD_STATUS_UNSPECIFIED
}

func (x *ExtractedField) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *ExtractedField) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            int32                  `protobuf:"varint,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            int32                  `protobuf:"varint,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            int32                  `protobuf:"varint,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            int32                  `protobuf:"varint,4,opt,name=y2,proto3" json:"y2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{7}
}

func (x *BoundingBox) GetX1() int32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *BoundingBox) GetY1() int32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *BoundingBox) GetX2() int32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *BoundingBox) GetY2() int32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

type Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // LOW_CONFIDENCE | VALIDATION_FAILED | PAGE_UNREADABLE | UNSUPPORTED_FILE_TYPE
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"` // for humans - consumers MUST NOT parse the detail contents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{8}
}

func (x *Issue) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Issue) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Issue) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // UNSUPPORTED_FILE_TYPE | FILE_CORRUPT | STORAGE_OBJECT_MISSING | RESOURCE_LIMIT | INTERNAL
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // for logging - not meant to be parsed by consumers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_document_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{9}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_document_proto protoreflect.FileDescriptor

const file_document_proto_rawDesc = "" +
	"\n" +
	"\x0edocument.proto\x12\vdocument.v1\"\xce\x01\n" +
	"\x15SubmitDocumentRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\fexternal_ref\x18\x02 \x01(\tR\vexternalRef\x12\x1b\n" +
	"\tschema_id\x18\x03 \x01(\tR\bschemaId\x12\x1b\n" +
	"\tcaller_id\x18\x04 \x01(\tR\bcallerId\x12/\n" +
	"\x06source\x18\x05 \x01(\v2\x17.document.v1.FileSourceR\x06source\"\x8b\x01\n" +
	"\n" +
	"FileSource\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12!\n" +
	"\fstorage_path\x18\x02 \x01(\tR\vstoragePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12#\n" +
	"\rdeclared_mime\x18\x04 \x01(\tR\fdeclaredMime\"n\n" +
	"\x16SubmitDocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.document.v1.DocumentStatusR\x06status\"5\n" +
	"\x12GetDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"\xca\x01\n" +
	"\x13GetDocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.document.v1.DocumentStatusR\x06status\x123\n" +
	"\x06result\x18\x03 \x01(\v2\x1b.document.v1.DocumentResultR\x06result\x12(\n" +
	"\x05error\x18\x04 \x01(\v2\x12.document.v1.ErrorR\x05error\"\xbf\x01\n" +
	"\x0eDocumentResult\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12%\n" +
	"\x0eavg_confidence\x18\x02 \x01(\x01R\ravgConfidence\x123\n" +
	"\x06fields\x18\x03 \x03(\v2\x1b.document.v1.ExtractedFieldR\x06fields\x12*\n" +
	"\x06issues\x18\x04 \x03(\v2\x12.document.v1.IssueR\x06issues\"\x82\x02\n" +
	"\x0eExtractedField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.document.v1.FieldStatusR\x06status\x12,\n" +
	"\x04bbox\x18\a \x01(\v2\x18.document.v1.BoundingBoxR\x04bbox\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\"M\n" +
	"\vBoundingBox\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x05R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x05R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x05R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x05R\x02y2\"I\n" +
	"\x05Issue\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xca\x01\n" +
	"\x0eDocumentStatus\x12\x1f\n" +
	"\x1bDOCUMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DOCUMENT_STATUS_QUEUED\x10\x01\x12\x1e\n" +
	"\x1aDOCUMENT_STATUS_PROCESSING\x10\x02\x12\x1d\n" +
	"\x19DOCUMENT_STATUS_COMPLETED\x10\x03\x12 \n" +
	"\x1cDOCUMENT_STATUS_NEEDS_REVIEW\x10\x04\x12\x1a\n" +
	"\x16DOCUMENT_STATUS_FAILED\x10\x05*\x9c\x01\n" +
	"\vFieldStatus\x12\x1c\n" +
	"\x18FIELD_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FIELD_STATUS_EXTRACTED\x10\x01\x12\x1f\n" +
	"\x1bFIELD_STATUS_LOW_CONFIDENCE\x10\x02\x12\x18\n" +
	"\x14FIELD_STATUS_MISSING\x10\x03\x12\x18\n" +
	"\x14FIELD_STATUS_INVALID\x10\x042\xbe\x01\n" +
	"\x0fDocumentService\x12Y\n" +
	"\x0eSubmitDocument\x12\".document.v1.SubmitDocumentRequest\x1a#.document.v1.SubmitDocumentResponse\x12P\n" +
	"\vGetDocument\x12\x1f.document.v1.GetDocumentRequest\x1a .document.v1.GetDocumentResponseB;Z9github.com/disillusioned-labs/platform/contract/ocr;ocrpbb\x06proto3"

var (
	file_document_proto_rawDescOnce sync.Once
	file_document_proto_rawDescData []byte
)

func file_document_proto_rawDescGZIP() []byte {
	file_document_proto_rawDescOnce.Do(func() {
		file_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)))
	})
	return file_document_proto_rawDescData
}

var file_document_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_document_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_document_proto_goTypes = []any{
	(DocumentStatus)(0),            // 0: document.v1.DocumentStatus
	(FieldStatus)(0),               // 1: document.v1.FieldStatus
	(*SubmitDocumentRequest)(nil),  // 2: document.v1.SubmitDocumentRequest
	(*FileSource)(nil),             // 3: document.v1.FileSource
	(*SubmitDocumentResponse)(nil), // 4: document.v1.SubmitDocumentResponse
	(*GetDocumentRequest)(nil),     // 5: document.v1.GetDocumentRequest
	(*GetDocumentResponse)(nil),    // 6: document.v1.GetDocumentResponse
	(*DocumentResult)(nil),         // 7: document.v1.DocumentResult
	(*ExtractedField)(nil),         // 8: document.v1.ExtractedField
	(*BoundingBox)(nil),            // 9: document.v1.BoundingBox
	(*Issue)(nil),                  // 10: document.v1.Issue
	(*Error)(nil),                  // 11: document.v1.Error
}
var file_document_proto_depIdxs = []int32{
	3,  // 0: document.v1.SubmitDocumentRequest.source:type_name -> document.v1.FileSource
	0,  // 1: document.v1.SubmitDocumentResponse.status:type_name -> document.v1.DocumentStatus
	0,  // 2: document.v1.GetDocumentResponse.status:type_name -> document.v1.DocumentStatus
	7,  // 3: document.v1.GetDocumentResponse.result:type_name -> document.v1.DocumentResult
	11, // 4: document.v1.GetDocumentResponse.error:type_name -> document.v1.Error
	8,  // 5: document.v1.DocumentResult.fields:type_name -> document.v1.ExtractedField
	10, // 6: document.v1.DocumentResult.issues:type_name -> document.v1.Issue
	1,  // 7: document.v1.ExtractedField.status:type_name -> document.v1.FieldStatus
	9,  // 8: document.v1.ExtractedField.bbox:type_name -> document.v1.BoundingBox
	2,  // 9: document.v1.DocumentService.SubmitDocument:input_type -> document.v1.SubmitDocumentRequest
	5,  // 10: document.v1.DocumentService.GetDocument:input_type -> document.v1.GetDocumentRequest
	4,  // 11: document.v1.DocumentService.SubmitDocument:output_type -> document.v1.SubmitDocumentResponse
	6,  // 12: document.v1.DocumentService.GetDocument:output_type -> document.v1.GetDocumentResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_document_proto_init() }
func file_document_proto_init() {
	if File_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_document_proto_goTypes,
		DependencyIndexes: file_document_proto_depIdxs,
		EnumInfos:         file_document_proto_enumTypes,
		MessageInfos:      file_document_proto_msgTypes,
	}.Build()
	File_document_proto = out.File
	file_document_proto_goTypes = nil
	file_document_proto_depIdxs = nil
}
