// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: contract/identity/identity.proto

package identitypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IsMemberActive
type IsMemberActiveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IsMemberActiveRequest) Reset() {
	*x = IsMemberActiveRequest{}
	mi := &file_contract_identity_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberActiveRequest) ProtoMessage() {}

func (x *IsMemberActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_identity_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberActiveRequest.ProtoReflect.Descriptor instead.
func (*IsMemberActiveRequest) Descriptor() ([]byte, []int) {
	return file_contract_identity_identity_proto_rawDescGZIP(), []int{0}
}

func (x *IsMemberActiveRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *IsMemberActiveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsMemberActiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"` // true = active, false = removed/left/deleted
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                          // "owner" | "admin" | "member"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberActiveResponse) Reset() {
	*x = IsMemberActiveResponse{}
	mi := &file_contract_identity_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberActiveResponse) ProtoMessage() {}

func (x *IsMemberActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_identity_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberActiveResponse.ProtoReflect.Descriptor instead.
func (*IsMemberActiveResponse) Descriptor() ([]byte, []int) {
	return file_contract_identity_identity_proto_rawDescGZIP(), []int{1}
}

func (x *IsMemberActiveResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *IsMemberActiveResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// GetMemberRole
type GetMemberRoleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMemberRoleRequest) Reset() {
	*x = GetMemberRoleRequest{}
	mi := &file_contract_identity_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRoleRequest) ProtoMessage() {}

func (x *GetMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_identity_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_contract_identity_identity_proto_rawDescGZIP(), []int{2}
}

func (x *GetMemberRoleRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetMemberRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "owner" | "admin" | "member"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRoleResponse) Reset() {
	*x = GetMemberRoleResponse{}
	mi := &file_contract_identity_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRoleResponse) ProtoMessage() {}

func (x *GetMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_identity_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*GetMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_contract_identity_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetMemberRoleResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// GetUsersInfo
type GetUsersInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // batch UUID users
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersInfoRequest) Reset() {
	*x = GetUsersInfoRequest{}
	mi := &file_contract_identity_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersInfoRequest) ProtoMessage() {}

func (x *GetUsersInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_identity_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUsersInfoRequest) Descriptor() ([]byte, []int) {
	return file_contract_identity_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsersInfoRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersInfoResponse) Reset() {
	*x = GetUsersInfoResponse{}
	mi := &file_contract_identity_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersInfoResponse) ProtoMessage() {}

func (x *GetUsersInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_identity_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUsersInfoResponse) Descriptor() ([]byte, []int) {
	return file_contract_identity_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsersInfoResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` //  organization role
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_contract_identity_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_contract_identity_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_contract_identity_identity_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// GetOrgStatus
type GetOrgStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrgStatusRequest) Reset() {
	*x = GetOrgStatusRequest{}
	mi := &file_contract_identity_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgStatusRequest) ProtoMessage() {}

func (x *GetOrgStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_identity_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOrgStatusRequest) Descriptor() ([]byte, []int) {
	return file_contract_identity_identity_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrgStatusRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetOrgStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFrozen      bool                   `protobuf:"varint,1,opt,name=is_frozen,json=isFrozen,proto3" json:"is_frozen,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,2,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgStatusResponse) Reset() {
	*x = GetOrgStatusResponse{}
	mi := &file_contract_identity_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgStatusResponse) ProtoMessage() {}

func (x *GetOrgStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_identity_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOrgStatusResponse) Descriptor() ([]byte, []int) {
	return file_contract_identity_identity_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrgStatusResponse) GetIsFrozen() bool {
	if x != nil {
		return x.IsFrozen
	}
	return false
}

func (x *GetOrgStatusResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

// IsServiceAccessAllowed
type IsServiceAccessAllowedRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ServiceName    string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IsServiceAccessAllowedRequest) Reset() {
	*x = IsServiceAccessAllowedRequest{}
	mi := &file_contract_identity_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsServiceAccessAllowedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsServiceAccessAllowedRequest) ProtoMessage() {}

func (x *IsServiceAccessAllowedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_identity_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsServiceAccessAllowedRequest.ProtoReflect.Descriptor instead.
func (*IsServiceAccessAllowedRequest) Descriptor() ([]byte, []int) {
	return file_contract_identity_identity_proto_rawDescGZIP(), []int{9}
}

func (x *IsServiceAccessAllowedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsServiceAccessAllowedRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *IsServiceAccessAllowedRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type IsServiceAccessAllowedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsServiceAccessAllowedResponse) Reset() {
	*x = IsServiceAccessAllowedResponse{}
	mi := &file_contract_identity_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsServiceAccessAllowedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsServiceAccessAllowedResponse) ProtoMessage() {}

func (x *IsServiceAccessAllowedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_identity_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsServiceAccessAllowedResponse.ProtoReflect.Descriptor instead.
func (*IsServiceAccessAllowedResponse) Descriptor() ([]byte, []int) {
	return file_contract_identity_identity_proto_rawDescGZIP(), []int{10}
}

func (x *IsServiceAccessAllowedResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_contract_identity_identity_proto protoreflect.FileDescriptor

const file_contract_identity_identity_proto_rawDesc = "" +
	"\n" +
	" contract/identity/identity.proto\x12\videntity.v1\"Y\n" +
	"\x15IsMemberActiveRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x16IsMemberActiveResponse\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"X\n" +
	"\x14GetMemberRoleRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"+\n" +
	"\x15GetMemberRoleResponse\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"0\n" +
	"\x13GetUsersInfoRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"C\n" +
	"\x14GetUsersInfoResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.identity.v1.UserInfoR\x05users\"~\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\">\n" +
	"\x13GetOrgStatusRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"R\n" +
	"\x14GetOrgStatusResponse\x12\x1b\n" +
	"\tis_frozen\x18\x01 \x01(\bR\bisFrozen\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x02 \x01(\bR\tisDeleted\"\x84\x01\n" +
	"\x1dIsServiceAccessAllowedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\":\n" +
	"\x1eIsServiceAccessAllowedResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed2\xe1\x03\n" +
	"\x0fIdentityService\x12Y\n" +
	"\x0eIsMemberActive\x12\".identity.v1.IsMemberActiveRequest\x1a#.identity.v1.IsMemberActiveResponse\x12V\n" +
	"\rGetMemberRole\x12!.identity.v1.GetMemberRoleRequest\x1a\".identity.v1.GetMemberRoleResponse\x12S\n" +
	"\fGetUsersInfo\x12 .identity.v1.GetUsersInfoRequest\x1a!.identity.v1.GetUsersInfoResponse\x12S\n" +
	"\fGetOrgStatus\x12 .identity.v1.GetOrgStatusRequest\x1a!.identity.v1.GetOrgStatusResponse\x12q\n" +
	"\x16IsServiceAccessAllowed\x12*.identity.v1.IsServiceAccessAllowedRequest\x1a+.identity.v1.IsServiceAccessAllowedResponseBEZCgithub.com/disillusioned-labs/platform/contract/identity;identitypbb\x06proto3"

var (
	file_contract_identity_identity_proto_rawDescOnce sync.Once
	file_contract_identity_identity_proto_rawDescData []byte
)

func file_contract_identity_identity_proto_rawDescGZIP() []byte {
	file_contract_identity_identity_proto_rawDescOnce.Do(func() {
		file_contract_identity_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_identity_identity_proto_rawDesc), len(file_contract_identity_identity_proto_rawDesc)))
	})
	return file_contract_identity_identity_proto_rawDescData
}

var file_contract_identity_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_contract_identity_identity_proto_goTypes = []any{
	(*IsMemberActiveRequest)(nil),          // 0: identity.v1.IsMemberActiveRequest
	(*IsMemberActiveResponse)(nil),         // 1: identity.v1.IsMemberActiveResponse
	(*GetMemberRoleRequest)(nil),           // 2: identity.v1.GetMemberRoleRequest
	(*GetMemberRoleResponse)(nil),          // 3: identity.v1.GetMemberRoleResponse
	(*GetUsersInfoRequest)(nil),            // 4: identity.v1.GetUsersInfoRequest
	(*GetUsersInfoResponse)(nil),           // 5: identity.v1.GetUsersInfoResponse
	(*UserInfo)(nil),                       // 6: identity.v1.UserInfo
	(*GetOrgStatusRequest)(nil),            // 7: identity.v1.GetOrgStatusRequest
	(*GetOrgStatusResponse)(nil),           // 8: identity.v1.GetOrgStatusResponse
	(*IsServiceAccessAllowedRequest)(nil),  // 9: identity.v1.IsServiceAccessAllowedRequest
	(*IsServiceAccessAllowedResponse)(nil), // 10: identity.v1.IsServiceAccessAllowedResponse
}
var file_contract_identity_identity_proto_depIdxs = []int32{
	6,  // 0: identity.v1.GetUsersInfoResponse.users:type_name -> identity.v1.UserInfo
	0,  // 1: identity.v1.IdentityService.IsMemberActive:input_type -> identity.v1.IsMemberActiveRequest
	2,  // 2: identity.v1.IdentityService.GetMemberRole:input_type -> identity.v1.GetMemberRoleRequest
	4,  // 3: identity.v1.IdentityService.GetUsersInfo:input_type -> identity.v1.GetUsersInfoRequest
	7,  // 4: identity.v1.IdentityService.GetOrgStatus:input_type -> identity.v1.GetOrgStatusRequest
	9,  // 5: identity.v1.IdentityService.IsServiceAccessAllowed:input_type -> identity.v1.IsServiceAccessAllowedRequest
	1,  // 6: identity.v1.IdentityService.IsMemberActive:output_type -> identity.v1.IsMemberActiveResponse
	3,  // 7: identity.v1.IdentityService.GetMemberRole:output_type -> identity.v1.GetMemberRoleResponse
	5,  // 8: identity.v1.IdentityService.GetUsersInfo:output_type -> identity.v1.GetUsersInfoResponse
	8,  // 9: identity.v1.IdentityService.GetOrgStatus:output_type -> identity.v1.GetOrgStatusResponse
	10, // 10: identity.v1.IdentityService.IsServiceAccessAllowed:output_type -> identity.v1.IsServiceAccessAllowedResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_contract_identity_identity_proto_init() }
func file_contract_identity_identity_proto_init() {
	if File_contract_identity_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_identity_identity_proto_rawDesc), len(file_contract_identity_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_identity_identity_proto_goTypes,
		DependencyIndexes: file_contract_identity_identity_proto_depIdxs,
		MessageInfos:      file_contract_identity_identity_proto_msgTypes,
	}.Build()
	File_contract_identity_identity_proto = out.File
	file_contract_identity_identity_proto_goTypes = nil
	file_contract_identity_identity_proto_depIdxs = nil
}
