// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: identity.proto

package identitypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_IsMemberActive_FullMethodName         = "/identity.v1.IdentityService/IsMemberActive"
	IdentityService_GetMemberRole_FullMethodName          = "/identity.v1.IdentityService/GetMemberRole"
	IdentityService_GetUsersInfo_FullMethodName           = "/identity.v1.IdentityService/GetUsersInfo"
	IdentityService_GetOrgStatus_FullMethodName           = "/identity.v1.IdentityService/GetOrgStatus"
	IdentityService_IsServiceAccessAllowed_FullMethodName = "/identity.v1.IdentityService/IsServiceAccessAllowed"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityServiceClient interface {
	IsMemberActive(ctx context.Context, in *IsMemberActiveRequest, opts ...grpc.CallOption) (*IsMemberActiveResponse, error)
	GetMemberRole(ctx context.Context, in *GetMemberRoleRequest, opts ...grpc.CallOption) (*GetMemberRoleResponse, error)
	GetUsersInfo(ctx context.Context, in *GetUsersInfoRequest, opts ...grpc.CallOption) (*GetUsersInfoResponse, error)
	GetOrgStatus(ctx context.Context, in *GetOrgStatusRequest, opts ...grpc.CallOption) (*GetOrgStatusResponse, error)
	IsServiceAccessAllowed(ctx context.Context, in *IsServiceAccessAllowedRequest, opts ...grpc.CallOption) (*IsServiceAccessAllowedResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) IsMemberActive(ctx context.Context, in *IsMemberActiveRequest, opts ...grpc.CallOption) (*IsMemberActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsMemberActiveResponse)
	err := c.cc.Invoke(ctx, IdentityService_IsMemberActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetMemberRole(ctx context.Context, in *GetMemberRoleRequest, opts ...grpc.CallOption) (*GetMemberRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberRoleResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUsersInfo(ctx context.Context, in *GetUsersInfoRequest, opts ...grpc.CallOption) (*GetUsersInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersInfoResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUsersInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetOrgStatus(ctx context.Context, in *GetOrgStatusRequest, opts ...grpc.CallOption) (*GetOrgStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrgStatusResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetOrgStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) IsServiceAccessAllowed(ctx context.Context, in *IsServiceAccessAllowedRequest, opts ...grpc.CallOption) (*IsServiceAccessAllowedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsServiceAccessAllowedResponse)
	err := c.cc.Invoke(ctx, IdentityService_IsServiceAccessAllowed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
type IdentityServiceServer interface {
	IsMemberActive(context.Context, *IsMemberActiveRequest) (*IsMemberActiveResponse, error)
	GetMemberRole(context.Context, *GetMemberRoleRequest) (*GetMemberRoleResponse, error)
	GetUsersInfo(context.Context, *GetUsersInfoRequest) (*GetUsersInfoResponse, error)
	GetOrgStatus(context.Context, *GetOrgStatusRequest) (*GetOrgStatusResponse, error)
	IsServiceAccessAllowed(context.Context, *IsServiceAccessAllowedRequest) (*IsServiceAccessAllowedResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) IsMemberActive(context.Context, *IsMemberActiveRequest) (*IsMemberActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsMemberActive not implemented")
}
func (UnimplementedIdentityServiceServer) GetMemberRole(context.Context, *GetMemberRoleRequest) (*GetMemberRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberRole not implemented")
}
func (UnimplementedIdentityServiceServer) GetUsersInfo(context.Context, *GetUsersInfoRequest) (*GetUsersInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsersInfo not implemented")
}
func (UnimplementedIdentityServiceServer) GetOrgStatus(context.Context, *GetOrgStatusRequest) (*GetOrgStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrgStatus not implemented")
}
func (UnimplementedIdentityServiceServer) IsServiceAccessAllowed(context.Context, *IsServiceAccessAllowedRequest) (*IsServiceAccessAllowedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsServiceAccessAllowed not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_IsMemberActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsMemberActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).IsMemberActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_IsMemberActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).IsMemberActive(ctx, req.(*IsMemberActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetMemberRole(ctx, req.(*GetMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUsersInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUsersInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUsersInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUsersInfo(ctx, req.(*GetUsersInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetOrgStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrgStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetOrgStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetOrgStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetOrgStatus(ctx, req.(*GetOrgStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_IsServiceAccessAllowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsServiceAccessAllowedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).IsServiceAccessAllowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_IsServiceAccessAllowed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).IsServiceAccessAllowed(ctx, req.(*IsServiceAccessAllowedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsMemberActive",
			Handler:    _IdentityService_IsMemberActive_Handler,
		},
		{
			MethodName: "GetMemberRole",
			Handler:    _IdentityService_GetMemberRole_Handler,
		},
		{
			MethodName: "GetUsersInfo",
			Handler:    _IdentityService_GetUsersInfo_Handler,
		},
		{
			MethodName: "GetOrgStatus",
			Handler:    _IdentityService_GetOrgStatus_Handler,
		},
		{
			MethodName: "IsServiceAccessAllowed",
			Handler:    _IdentityService_IsServiceAccessAllowed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}
